<?php

namespace Drupal\elasticsearch_helper_content;

use Drupal\Core\Field\FieldItemInterface;
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Class FieldNormalizerBase
 */
abstract class ElasticsearchFieldNormalizerBase extends ElasticsearchNormalizerBase implements ElasticsearchFieldNormalizerInterface {

  /**
   * @var \Drupal\elasticsearch_helper_content\ElasticsearchNormalizerHelper
   */
  protected $normalizerHelper;

  /**
   * @var string
   */
  protected $targetEntityType;

  /**
   * @var string
   */
  protected $targetBundle;

  /**
   * ElasticsearchFieldNormalizerBase constructor.
   *
   * @param array $configuration
   * @param $plugin_id
   * @param $plugin_definition
   * @param \Drupal\elasticsearch_helper_content\ElasticsearchNormalizerHelper $normalizer_helper
   */
  public function __construct(array $configuration, $plugin_id, $plugin_definition, ElasticsearchNormalizerHelper $normalizer_helper) {
    if (!isset($configuration['entity_type'], $configuration['bundle'])) {
      throw new \InvalidArgumentException(t('Entity type or bundle key is not provided in plugin configuration.'));
    }

    $this->targetEntityType = $configuration['entity_type'];
    $this->targetBundle = $configuration['bundle'];
    unset($configuration['entity_type'], $configuration['bundle']);

    parent::__construct($configuration, $plugin_id, $plugin_definition);
    $this->normalizerHelper = $normalizer_helper;
  }

  public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition) {
    return new static(
      $configuration,
      $plugin_id,
      $plugin_definition,
      $container->get('elasticsearch_helper_content.normalizer_helper')
    );
  }

  /**
   * {@inheritdoc}
   */
  public function normalize($object, array $context = []) {
    $result = [];

    try {
      $cardinality = $this->getCardinality($object);

      foreach ($object as $item) {
        $value = $this->getFieldItemValue($item, $context);

        if ($cardinality === 1) {
          return $value;
        }

        // Do not pass empty strings.
        if ($value !== '') {
          $result[] = $value;
        }
      }
    }
    catch (\Exception $e) {
      watchdog_exception('elasticsearch_helper_content', $e);
    }

    return $result;
  }

  /**
   * @param \Drupal\Core\Field\FieldItemListInterface $item_list
   *
   * @return int
   */
  protected function getCardinality($item_list) {
    return $item_list->getFieldDefinition()->getFieldStorageDefinition()->getCardinality();
  }

  /**
   * Returns value of the field item.
   *
   * @param \Drupal\Core\Field\FieldItemInterface $item
   * @param array $context Context options for the normalizer
   *
   * @return mixed
   */
  public function getFieldItemValue(FieldItemInterface $item, array $context = []) {
    return '';
  }

  /**
   * {@inheritdoc}
   */
  public function buildConfigurationForm(array $form, FormStateInterface $form_state) {
    $pause = '';
    return [
      'render_value' => [
        '#type' => 'checkbox',
        '#title' => t('Store rendered value'),
        '#weight' => 50,
        '#default_value' => $this->configuration['render_value'],
      ],
      'render_view_mode' => [
        '#type' => 'select',
        '#title' => t('Render view mode'),
        '#weight' => 51,
        '#default_value' => $this->configuration['render_view_mode'],
        '#options' => $this->normalizerHelper->getEntityViewDisplayOptions(
          $this->targetEntityType,
          $this->targetBundle
        ),
        '#states' => [
          'invisible' => [
            ':input[name*="render_value"]' => [
              'checked' => FALSE,
            ]
          ],
        ],
      ],
    ] + parent::buildConfigurationForm($form, $form_state);
  }

  /**
   * {@inheritdoc}
   */
  public function defaultConfiguration() {
    return [
      'render_value' => FALSE,
      'render_view_mode' => 'default',
    ] + parent::defaultConfiguration(); // TODO: Change the autogenerated stub
  }

  /**
   * {@inheritdoc}
   */
  public function submitConfigurationForm(array &$form, FormStateInterface $form_state) {
    $this->configuration['render_value'] = $form_state->getValue('render_value');
    $this->configuration['render_view_mode'] = $form_state->getValue('render_view_mode');
    parent::submitConfigurationForm($form, $form_state);
  }

}
